---
- name: install squid
  package:
    name: "squid"
    state: present
  register: squid_install_squid
  until: squid_install_squid is succeeded
  retries: 3

- name: configure squid
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
  notify:
    - verify squid configuration
    - restart squid

- name: flush_handlers
  meta: flush_handlers

- name: start and enable squid
  service:
    name: "squid"
    state: started
    enabled: yes
